services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "9000:8080"
    environment:
      - JENKINS_OPTS="--httpPort=8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - C:/Users/cksdb/OneDrive/Desktop/apache-jmeter-5.6.3:/opt/jmeter  # 이 줄을 추가하세요!
   
    user: root
volumes:
  jenkins_home:
